[build]
builder = "NIXPACKS"
buildCommand = "unset NODE_ENV && pnpm install --no-frozen-lockfile && pnpm --filter @workspace/api-server run build"

[deploy]
startCommand = "node --enable-source-maps ./artifacts/api-server/dist/index.mjs"
