import { Router, type IRouter } from "express";
import healthRouter from "./health";
import accountHealthRouter from "./account-health";
import authRouter from "./auth";
import carouselRouter from "./carousel";
import contentRouter from "./content";
import presetsRouter from "./presets";
import captionsRouter from "./captions";
import calendarRouter from "./calendar";
import analyticsRouter from "./analytics";
import approvalRouter from "./approval";
import metaRouter from "./meta";
import metaAuthRouter from "./meta-auth";
import videoOverlayRouter from "./video-overlay";
import portalRouter from "./portal";
import schedulerRouter from "./scheduler";
import libraryRouter from "./library";
import onboardingRouter from "./onboarding";
import aboutMeRouter from "./about-me";
import seamlessCarouselRouter from "./seamless-caro-builder";
import aiPortraitRouter from "./aiPortrait";
import dmAutomationsRouter from "./dm-automations";
import webhooksRouter from "./webhooks";
import intakeRouter from "./intake";
import bulkImportRouter from "./bulkImport";
import dmPromptsRouter from "./dm-prompts";
import reelScriptsRouter from "./reel-scripts";
import bundleRouter from "./bundle";
import bundleRequestsRouter from "./bundle-requests";
import clubSignupsRouter from "./club-signups";
import coffeeRequestsRouter from "./coffee-requests";
import strategyTopicsRouter from "./strategy-topics";
import contentPreviewRouter from "./content-preview";
import storiesRouter from "./stories";
import stickersRouter from "./stickers";
import canvaRouter from "./canva";
import waitlistRouter from "./waitlist";
import approvalBundlesRouter from "./approvalBundles";
import contentGeneratorRouter from "./content-generator";
import memeRouter from "./meme";
import hookImageRouter from "./hook-image";
import notifyRouter from "./notify";
import submissionsRouter from "./submissions";
import revenueIdeasRouter from "./revenue-ideas";
import clientNewsRouter from "./client-news";
import homeworkRouter from "./homework";
import bonusContentRouter from "./bonus-content";
import blogRouter from "./blog";
import broadcastTopicsRouter from "./broadcast-topics";
import broadcastDraftsRouter from "./broadcast-drafts";
import reportsRouter from "./reports";
import dailyFocusRouter from "./daily-focus";
import captionGeneratorRouter from "./caption-generator";
import backgroundBuilderRouter from "./background-builder";
import highlightCoversRouter from "./highlight-covers";
import veoRouter from "./veo";
import googleAuthRouter from "./google-auth";
import brainstormRouter from "./brainstorm";

const router: IRouter = Router();

router.use(healthRouter);
router.use(accountHealthRouter);
router.use(authRouter);
router.use(carouselRouter);
router.use(contentRouter);
router.use(presetsRouter);
router.use(captionsRouter);
router.use(calendarRouter);
router.use(analyticsRouter);
router.use(approvalRouter);
router.use(metaRouter);
router.use(metaAuthRouter);
router.use(videoOverlayRouter);
router.use(portalRouter);
router.use(schedulerRouter);
router.use(libraryRouter);
router.use(onboardingRouter);
router.use(aboutMeRouter);
router.use(seamlessCarouselRouter);
router.use(backgroundBuilderRouter);
router.use(highlightCoversRouter);
router.use(aiPortraitRouter);
router.use(memeRouter);
router.use(hookImageRouter);
router.use(notifyRouter);
router.use(submissionsRouter);
router.use(dmAutomationsRouter);
router.use(webhooksRouter);
router.use(intakeRouter);
router.use(bulkImportRouter);
router.use(dmPromptsRouter);
router.use(reelScriptsRouter);
router.use(bundleRouter);
router.use(bundleRequestsRouter);
router.use(clubSignupsRouter);
router.use(coffeeRequestsRouter);
router.use(strategyTopicsRouter);
router.use(contentPreviewRouter);
router.use(storiesRouter);
router.use(stickersRouter);
router.use(canvaRouter);
router.use(googleAuthRouter);
router.use(brainstormRouter);
router.use(waitlistRouter);
router.use(approvalBundlesRouter);
router.use(contentGeneratorRouter);
router.use(revenueIdeasRouter);
router.use(clientNewsRouter);
router.use(homeworkRouter);
router.use(bonusContentRouter);
router.use(blogRouter);
router.use(broadcastTopicsRouter);
router.use(broadcastDraftsRouter);
router.use(reportsRouter);
router.use(dailyFocusRouter);
router.use(captionGeneratorRouter);
router.use(veoRouter);

export default router;
