// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/carousel-toolbar/CarouselToolbar.tsx": () => import("../components/mockups/carousel-toolbar/CarouselToolbar.tsx")
};
